import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { collectGitEvidence } from "./evidence.js";

export const SUPPORTED_SCANNERS=new Set(["code-review","lucapi-secret","gitleaks","semgrep","trivy","osv-scanner","sonarqube"]);
function containsUnmanagedSecret(value,path=[]){if(!value||typeof value!=="object")return false;return Object.entries(value).some(([key,item])=>{const next=[...path,key],secret=/(token|password|secret|authorization|api.?key)/i.test(key)&&item!==null&&item!=="";return secret&&!["sonarqube.token","sonarqube.hasToken"].includes(next.join("."))||containsUnmanagedSecret(item,next);});}
export function validateScanProfileInput(input){if(!input?.name)throw new Error("Scan profile name is required");if(!["review","manual","pre-dev","post-dev"].includes(input.hook??"review"))throw new Error("Unsupported scan hook");if(!Array.isArray(input.scanners)||!input.scanners.length||input.scanners.some((s)=>!SUPPORTED_SCANNERS.has(s)))throw new Error("Scan profile contains an unsupported scanner");if(containsUnmanagedSecret(input.config))throw new Error("Scan config contains an unmanaged secret field");if(input.config?.execution&&!['host','docker'].includes(input.config.execution))throw new Error("Scan execution must be host or docker");for(const image of Object.values(input.config?.images??{}))if(typeof image!=="string"||image.length>300||/[\x00-\x20;&|`$<>]/.test(image))throw new Error("Scanner image reference is invalid");if(input.scanners.includes("sonarqube")&&input.config?.sonarqube?.serverUrl){const url=new URL(input.config.sonarqube.serverUrl);if(!["http:","https:"].includes(url.protocol)||url.username||url.password)throw new Error("SonarQube URL must be HTTP(S) without embedded credentials");}const validSeverities=new Set(["critical","high","medium","low","info"]);if((input.policy?.blockOn??[]).some((s)=>!validSeverities.has(s)))throw new Error("Scan blockOn contains an invalid severity");return input;}

const SEVERITY={error:"high",warning:"medium",note:"low",critical:"critical",high:"high",medium:"medium",moderate:"medium",low:"low",info:"info",blocker:"critical",major:"high",minor:"medium"};
export function normalizeSeverity(value){return SEVERITY[String(value??"medium").toLowerCase()]??"medium";}
function redactRaw(value,depth=0){if(depth>8)return"[truncated]";if(Array.isArray(value))return value.slice(0,200).map((item)=>redactRaw(item,depth+1));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,/(token|password|secret|authorization|api.?key)/i.test(key)?"[redacted]":redactRaw(item,depth+1)]));if(typeof value==="string"){const redacted=value.replace(/(Bearer\s+)[A-Za-z0-9._-]+/gi,"$1[redacted]").replace(/((?:token|password|secret|api.?key)=)[^&\s]+/gi,"$1[redacted]");return redacted.length>4000?`${redacted.slice(0,4000)}…`:redacted;}return value;}
function fingerprint(f){return createHash("sha256").update([f.scanner,f.ruleId,f.file,f.startLine,f.message].join("|")).digest("hex");}
function finding(input){const f={scanner:input.scanner,ruleId:String(input.ruleId??"unknown").slice(0,300),severity:normalizeSeverity(input.severity),category:String(input.category??"quality").slice(0,100),file:input.file?String(input.file).slice(0,1000):null,startLine:Number(input.startLine)||null,endLine:Number(input.endLine)||null,message:redactRaw(String(input.message??"Scanner finding")),isNew:input.isNew!==false,suppressed:input.suppressed===true,raw:redactRaw(input.raw??null)};return{...f,fingerprint:input.fingerprint??fingerprint(f)};}
function exec(command,args,cwd,timeoutMs=300_000,extraEnv={},signal=null){return new Promise((resolve)=>{const started=Date.now();execFile(command,args,{cwd,timeout:timeoutMs,signal,maxBuffer:16*1024*1024,env:{...process.env,...extraEnv}},(error,stdout,stderr)=>resolve({exitCode:error?.code&&Number.isInteger(error.code)?error.code:error?1:0,stdout:String(stdout),stderr:String(stderr),durationMs:Date.now()-started,error:error?.message}));});}
async function fetchJson(url,options={},timeoutMs=30_000,externalSignal=null){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs),abort=()=>controller.abort();externalSignal?.addEventListener("abort",abort,{once:true});try{const response=await fetch(url,{...options,signal:controller.signal}),text=await response.text();if(!response.ok)throw new Error(`HTTP ${response.status}: ${text.slice(0,300)}`);return text?JSON.parse(text):null;}finally{clearTimeout(timer);externalSignal?.removeEventListener("abort",abort);}}
function sarifFindings(sarif,scanner="sarif"){
  const results=[];for(const run of sarif?.runs??[]){const rules=new Map((run.tool?.driver?.rules??[]).map((r)=>[r.id,r]));for(const result of run.results??[]){const location=result.locations?.[0]?.physicalLocation,region=location?.region,rule=rules.get(result.ruleId);results.push(finding({scanner:run.tool?.driver?.name??scanner,ruleId:result.ruleId,severity:result.level??rule?.defaultConfiguration?.level,category:rule?.properties?.tags?.[0]??"security",file:location?.artifactLocation?.uri,startLine:region?.startLine,endLine:region?.endLine,message:result.message?.text??result.message?.markdown}));}}return results;
}
export function findingsToSarif(findings){return{$schema:"https://json.schemastore.org/sarif-2.1.0.json",version:"2.1.0",runs:[{tool:{driver:{name:"LucaPi",informationUri:"https://github.com/jeffreymu/luca",rules:[...new Map(findings.map((f)=>[`${f.scanner}:${f.rule_id??f.ruleId}`,{id:`${f.scanner}:${f.rule_id??f.ruleId}`,shortDescription:{text:f.message}}])).values()]}},results:findings.map((f)=>({ruleId:`${f.scanner}:${f.rule_id??f.ruleId}`,level:["critical","high"].includes(f.severity)?"error":f.severity==="medium"?"warning":"note",message:{text:f.message},locations:f.file?[{physicalLocation:{artifactLocation:{uri:f.file},region:{startLine:f.start_line??f.startLine??1,endLine:f.end_line??f.endLine??f.start_line??f.startLine??1}}}]:[]}))}]};}
function parseGitleaks(data){return(data??[]).map((r)=>finding({scanner:"gitleaks",ruleId:r.RuleID,severity:"high",category:"secret",file:r.File,startLine:r.StartLine,endLine:r.EndLine,message:r.Description??`Secret detected: ${r.RuleID}`,fingerprint:r.Fingerprint}));}
function parseSemgrep(data){return(data?.results??[]).map((r)=>finding({scanner:"semgrep",ruleId:r.check_id,severity:r.extra?.severity,category:r.extra?.metadata?.category??"sast",file:r.path,startLine:r.start?.line,endLine:r.end?.line,message:r.extra?.message}));}
function parseTrivy(data){const findings=[];for(const result of data?.Results??[]){for(const v of result.Vulnerabilities??[])findings.push(finding({scanner:"trivy",ruleId:v.VulnerabilityID,severity:v.Severity,category:"dependency",file:result.Target,message:`${v.PkgName} ${v.InstalledVersion}: ${v.Title??v.Description??v.VulnerabilityID}`}));for(const m of result.Misconfigurations??[])findings.push(finding({scanner:"trivy",ruleId:m.ID,severity:m.Severity,category:"iac",file:result.Target,startLine:m.CauseMetadata?.StartLine,endLine:m.CauseMetadata?.EndLine,message:m.Title??m.Message}));}return findings;}
function parseOsv(data){const findings=[];for(const result of data?.results??[])for(const pkg of result.packages??[])for(const v of pkg.vulnerabilities??[])findings.push(finding({scanner:"osv-scanner",ruleId:v.id,severity:v.database_specific?.severity??"high",category:"dependency",file:result.source?.path,message:`${pkg.package?.name??"dependency"}: ${v.summary??v.id}`}));return findings;}
function internalSecretFindings(git){const results=[],patterns=[{id:"private-key",regex:/BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY/,message:"Private key detected"},{id:"aws-access-key",regex:/AKIA[0-9A-Z]{16}/,message:"AWS access key detected"},{id:"credential-assignment",regex:/(?:api[_-]?key|token|password)\s*[=:]\s*["']?[A-Za-z0-9_\-]{20,}/i,message:"Credential-like value detected"}];for(const p of patterns)if(p.regex.test(git.diff))results.push(finding({scanner:"lucapi-secret",ruleId:p.id,severity:"high",category:"secret",message:p.message}));for(const file of git.changedFiles.filter((f)=>/(^|\/)(\.env(?:\.|$)|id_rsa$|.*\.pem$)/i.test(f)))results.push(finding({scanner:"lucapi-secret",ruleId:"sensitive-file",severity:"high",category:"secret",file,message:"Sensitive file changed"}));return results;}
async function sonarScan({root,config,signal}){
  if(!config.serverUrl||!config.projectKey)throw new Error("SonarQube config requires serverUrl and projectKey");const token=config.token??"",args=[`-Dsonar.host.url=${config.serverUrl}`,`-Dsonar.projectKey=${config.projectKey}`,...(config.organization?[`-Dsonar.organization=${config.organization}`]:[]),...(config.branch? [`-Dsonar.branch.name=${config.branch}`]:[]),...(config.pullRequest? [`-Dsonar.pullrequest.key=${config.pullRequest.key}`,`-Dsonar.pullrequest.branch=${config.pullRequest.branch}`,`-Dsonar.pullrequest.base=${config.pullRequest.base}`]:[])];const execution=await exec("sonar-scanner",args,root,config.timeoutMs??600_000,token?{SONAR_TOKEN:token}:{},signal);if(execution.exitCode!==0)throw new Error(`sonar-scanner failed: ${execution.stderr.slice(-2000)}`);
  const task=Object.fromEntries((await readFile(path.join(root,".scannerwork","report-task.txt"),"utf8")).split("\n").filter(Boolean).map((l)=>{const i=l.indexOf("=");return[l.slice(0,i),l.slice(i+1)];})),headers=token?{authorization:`Bearer ${token}`}:{},deadline=Date.now()+(config.timeoutMs??600_000);let ce;
  while(Date.now()<deadline){ce=(await fetchJson(task.ceTaskUrl,{headers},30_000,signal)).task;if(ce.status==="SUCCESS")break;if(["FAILED","CANCELED"].includes(ce.status))throw new Error(`Sonar Compute Engine ${ce.status}`);await new Promise((r)=>setTimeout(r,1500));}if(ce?.status!=="SUCCESS")throw new Error("Sonar Compute Engine timeout");
  const gate=(await fetchJson(`${config.serverUrl.replace(/\/$/,"")}/api/qualitygates/project_status?analysisId=${encodeURIComponent(ce.analysisId)}`,{headers},30_000,signal)).projectStatus,issues=(await fetchJson(`${config.serverUrl.replace(/\/$/,"")}/api/issues/search?componentKeys=${encodeURIComponent(config.projectKey)}&resolved=false&ps=500`,{headers},30_000,signal)).issues??[];let hotspots=[];try{hotspots=(await fetchJson(`${config.serverUrl.replace(/\/$/,"")}/api/hotspots/search?projectKey=${encodeURIComponent(config.projectKey)}&status=TO_REVIEW&ps=500`,{headers},30_000,signal)).hotspots??[];}catch(error){if(config.requireHotspots)throw error;}const findings=issues.map((i)=>finding({scanner:"sonarqube",ruleId:i.rule,severity:i.severity,category:i.type?.toLowerCase()??"quality",file:i.component?.split(":").slice(1).join(":"),startLine:i.line,message:i.message}));for(const hotspot of hotspots)findings.push(finding({scanner:"sonarqube",ruleId:hotspot.ruleKey??"security-hotspot",severity:hotspot.vulnerabilityProbability??"medium",category:"security-hotspot",file:hotspot.component?.split(":").slice(1).join(":"),startLine:hotspot.line,message:hotspot.message??"Security hotspot requires review"}));if(gate.status!=="OK")findings.push(finding({scanner:"sonarqube",ruleId:"quality-gate",severity:"high",category:"quality-gate",message:`SonarQube Quality Gate: ${gate.status}`}));return{findings,metadata:{gate,task}};
}
export class ScanService{
  constructor(store){this.store=store;}
  async executeScanner(name,context){
    const {root,git,profile,provider,signal}=context,temp=await mkdtemp(path.join(os.tmpdir(),"lucapi-scan-"));try{
      if(name==="code-review"){if(!provider?.complete)return{findings:[finding({scanner:name,ruleId:"provider-unavailable",severity:"high",category:"scanner",message:"Code review provider unavailable"})]};const result=await provider.complete({system:"Review the supplied acceptance criteria and real git diff. Return JSON {verdict,findings:[{ruleId,severity,category,file,startLine,endLine,message}]}",user:`Acceptance criteria: ${JSON.stringify(context.acceptanceCriteria??[])}\nDiff:\n${git.diff.slice(0,60000)}`,signal}),items=(result.findings??[]).map((f)=>finding({scanner:name,...f}));if(result.verdict!=="APPROVED"&&!items.length)items.push(finding({scanner:name,ruleId:"review-not-approved",severity:"high",category:"quality",message:"Independent code review did not approve the change"}));return{findings:items,metadata:{verdict:result.verdict}};}
      if(name==="lucapi-secret")return{findings:internalSecretFindings(git)};
      if(name==="sonarqube")return sonarScan({root,config:profile.config?.sonarqube??profile.config??{},signal});
      const report=path.join(temp,"report.json"),hostCommands={gitleaks:["gitleaks",["detect","--source",root,"--report-format","json","--report-path",report,"--no-banner"]],semgrep:["semgrep",["scan","--json","--output",report,root]],trivy:["trivy",["fs","--format","json","--output",report,root]],"osv-scanner":["osv-scanner",["scan","--format","json","--output",report,root]]},dockerImages={gitleaks:"zricethezav/gitleaks:v8.24.2",semgrep:"semgrep/semgrep:1.100.0",trivy:"aquasec/trivy:0.58.2","osv-scanner":"ghcr.io/google/osv-scanner:v2.0.1"},dockerArgs={gitleaks:["detect","--source","/src","--report-format","json","--report-path","/out/report.json","--no-banner"],semgrep:["semgrep","scan","--json","--output","/out/report.json","/src"],trivy:["fs","--format","json","--output","/out/report.json","/src"],"osv-scanner":["scan","--format","json","--output","/out/report.json","/src"]};let definition=hostCommands[name];if(profile.config?.execution==="docker"&&definition)definition=["docker",["run","--rm","--network",profile.config.network===true?"bridge":"none","--memory",profile.config.memory??"2g","--cpus","2","--cap-drop","ALL","--security-opt","no-new-privileges","-v",`${root}:/src:ro`,`-v`,`${temp}:/out`,profile.config?.images?.[name]??dockerImages[name],...dockerArgs[name]]];if(!definition)throw new Error(`Unknown scanner: ${name}`);const execution=await exec(definition[0],definition[1],root,profile.config?.timeoutMs??300_000,{},signal);let data=null;try{data=JSON.parse(await readFile(report,"utf8"));}catch{if(execution.exitCode!==0)throw new Error(`${name} unavailable or failed: ${execution.stderr.slice(-1000)||execution.error}`);return{findings:[]};}const parsers={gitleaks:parseGitleaks,semgrep:parseSemgrep,trivy:parseTrivy,"osv-scanner":parseOsv};return{findings:parsers[name](data),metadata:{exitCode:execution.exitCode,durationMs:execution.durationMs}};
    }finally{await rm(temp,{recursive:true,force:true});}
  }
  async runProfile({profile,workspace,card=null,root=workspace.repo_path,baseCommit=null,headCommit=null,provider=null,acceptanceCriteria=[],shouldCancel=()=>false}){
    if((profile.config?.network===true||profile.scanners.includes("sonarqube"))&&!this.store.consumeNextOperationApproval(workspace.id,"scan.network",profile.id)){const pending=this.store.listOperationApprovals(workspace.id).find((a)=>a.operation==="scan.network"&&a.resource_id===profile.id&&a.status==="PENDING");if(!pending)this.store.createOperationApproval({workspaceId:workspace.id,operation:"scan.network",resourceId:profile.id,payload:{profile:profile.name,scanners:profile.scanners,execution:profile.config.execution??"host",images:profile.config.images??{}}});throw new Error("Networked scan requires an approved scan.network operation approval");}
    const git=await collectGitEvidence(root,baseCommit),run=this.store.createScanRun({workspaceId:workspace.id,cardId:card?.id,profileId:profile.id,baseCommit,headCommit:headCommit??git.headCommit}),scannerResults={},all=[];let infrastructureFailed=false;const controller=new AbortController(),cancelTimer=setInterval(()=>{if(shouldCancel())controller.abort();},100);cancelTimer.unref?.();
    try{for(const scanner of profile.scanners){if(shouldCancel())throw new Error("Scan cancelled by operator");try{const result=await this.executeScanner(scanner,{root,git,profile,provider,acceptanceCriteria,signal:controller.signal});scannerResults[scanner]={ok:true,count:result.findings.length,metadata:redactRaw(result.metadata)};all.push(...result.findings);}catch(error){if(shouldCancel()||controller.signal.aborted)throw error;scannerResults[scanner]={ok:false,error:redactRaw(error.message)};if(profile.policy?.failOnScannerError!==false){infrastructureFailed=true;all.push(finding({scanner,ruleId:"scanner-error",severity:"high",category:"scanner",message:error.message}));}}}const severityRank={critical:0,high:1,medium:2,low:3,info:4},totalBeforeLimit=all.length;all.sort((a,b)=>severityRank[a.severity]-severityRank[b.severity]);if(all.length>5000)all.length=5000;const known=this.store.knownScanFingerprints(profile.id,run.id),suppressed=this.store.suppressedScanFingerprints(workspace.id);for(const item of all){item.isNew=!known.has(item.fingerprint);item.suppressed=suppressed.has(item.fingerprint);this.store.addScanFinding(run.id,item);}const blockOn=profile.policy?.blockOn??["critical","high"],blocking=all.filter((f)=>!f.suppressed&&(!profile.policy?.newFindingsOnly||f.isNew)&&blockOn.includes(f.severity)),status=infrastructureFailed?"FAILED":blocking.length?"BLOCKED":"PASSED",summary={status,total:all.length,totalBeforeLimit,truncated:totalBeforeLimit>all.length,blocking:blocking.length,scanners:scannerResults};return this.store.finishScanRun(run.id,status,summary);}catch(error){this.store.finishScanRun(run.id,shouldCancel()?"CANCELLED":"FAILED",{error:redactRaw(error.message),scanners:scannerResults});throw error;}finally{clearInterval(cancelTimer);}
  }
  async runWorkspaceProfiles({workspace,hook="manual",card=null,root,baseCommit,headCommit,provider,acceptanceCriteria=[],shouldCancel=()=>false}){const profiles=this.store.listScanProfiles(workspace.id,{hook,enabledOnly:true}),runs=[];for(const profile of profiles)runs.push(await this.runProfile({profile,workspace,card,root:root??workspace.repo_path,baseCommit,headCommit,provider,acceptanceCriteria,shouldCancel}));return runs;}
  importSarif({workspaceId,cardId=null,sarif,profileId=null}){if(!this.store.getWorkspace(workspaceId))throw new Error("Workspace not found");const run=this.store.createScanRun({workspaceId,cardId,profileId}),items=sarifFindings(sarif).slice(0,5000);for(const item of items)this.store.addScanFinding(run.id,item);return this.store.finishScanRun(run.id,items.some((f)=>["critical","high"].includes(f.severity))?"BLOCKED":"PASSED",{status:"IMPORTED",total:items.length,blocking:items.filter((f)=>["critical","high"].includes(f.severity)).length});}
  exportSarif(runId){const run=this.store.getScanRun(runId);if(!run)throw new Error("Scan run not found");return findingsToSarif(run.findings);}
}
