import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { lstat, mkdtemp, readFile, readdir, realpath, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { SUPPORTED_SCANNERS, validateScanProfileInput } from "./scan-service.js";

const ALLOWED_HOOKS=new Set(["pre-dev","post-dev","review","manual"]);
const ALLOWED_TOOLS=new Set(["read_file","write_file","list_files","search_files","run_command","git_status","git_diff"]);
function exec(command,args,cwd,timeout=120_000){return new Promise((resolve,reject)=>execFile(command,args,{cwd,timeout,maxBuffer:4*1024*1024,env:{...process.env,GIT_TERMINAL_PROMPT:"0"}},(error,stdout,stderr)=>error?reject(new Error(`${command} failed: ${String(stderr||error.message).slice(-2000)}`)):resolve(String(stdout).trim())));}
function scalar(value){const v=value.trim();if(v==="true")return true;if(v==="false")return false;if(/^\d+(?:\.\d+)*$/.test(v))return v;if((v.startsWith("[")&&v.endsWith("]"))||(v.startsWith("{")&&v.endsWith("}"))){try{return JSON.parse(v);}catch{}}return v.replace(/^['"]|['"]$/g,"");}
export function parseSkillMarkdown(markdown){
  const match=String(markdown).match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/),frontmatter={};
  if(match)for(const line of match[1].split("\n")){const index=line.indexOf(":");if(index>0)frontmatter[line.slice(0,index).trim()]=scalar(line.slice(index+1));}
  return{frontmatter,body:(match?match[2]:String(markdown)).trim()};
}
function containsSecretField(value){if(!value||typeof value!=="object")return false;return Object.entries(value).some(([key,item])=>/(token|password|secret|authorization|api.?key)/i.test(key)&&item!==null&&item!==""||containsSecretField(item));}
export function validateManifest(input,defaults={}){
  const manifest={name:input?.name??defaults.name,version:String(input?.version??defaults.version??"1.0.0"),description:input?.description??defaults.description??"",hooks:input?.hooks??defaults.hooks??["manual"],tools:input?.tools??defaults.tools??[],commands:input?.commands??defaults.commands??[],scanners:input?.scanners??defaults.scanners??[],policy:input?.policy??defaults.policy??{},config:input?.config??defaults.config??{},outputs:input?.outputs??defaults.outputs??{format:"lucapi-findings-v1"},sandbox:input?.sandbox??defaults.sandbox??{network:false}};
  if(!/^[a-z0-9][a-z0-9-]{1,63}$/.test(manifest.name??""))throw new Error("Skill name must be 2-64 lowercase letters, digits or hyphens");
  if(!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(manifest.version))throw new Error("Skill version must be semver");
  if(!Array.isArray(manifest.hooks)||manifest.hooks.some((h)=>!ALLOWED_HOOKS.has(h)))throw new Error("Skill hooks contain an unsupported lifecycle hook");
  if(!Array.isArray(manifest.tools)||manifest.tools.some((t)=>!ALLOWED_TOOLS.has(t)))throw new Error("Skill requests an unsupported tool");
  if(!Array.isArray(manifest.commands)||manifest.commands.some((c)=>typeof c!=="string"||!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(c)))throw new Error("Skill commands must be safe executable names");
  if(containsSecretField(manifest.config))throw new Error("Skill manifest must not contain secret configuration values");
  if(manifest.sandbox?.network!==true)manifest.sandbox={...manifest.sandbox,network:false};
  return manifest;
}
async function snapshotDirectory(root){
  const actualRoot=await realpath(root),files={},queue=[actualRoot];let bytes=0;
  while(queue.length){const dir=queue.shift();for(const entry of await readdir(dir,{withFileTypes:true})){if([".git","node_modules"].includes(entry.name))continue;const absolute=path.join(dir,entry.name),stat=await lstat(absolute);if(stat.isSymbolicLink())throw new Error("Skill package cannot contain symbolic links");if(stat.isDirectory()){queue.push(absolute);continue;}if(!stat.isFile())continue;const relative=path.relative(actualRoot,absolute);if(Object.keys(files).length>=100)throw new Error("Skill package exceeds 100 files");const content=await readFile(absolute,"utf8");bytes+=Buffer.byteLength(content);if(bytes>1_048_576)throw new Error("Skill package exceeds 1 MiB");files[relative]=content;}}
  if(!files["SKILL.md"])throw new Error("Skill package must contain SKILL.md");return files;
}
function checksum(value){return createHash("sha256").update(value).digest("hex");}
export class SkillService{
  constructor(store){this.store=store;}
  async importSkill({workspaceId,source,approvalId=null}){
    if(!workspaceId||!source?.type)throw new Error("workspaceId and source.type are required");const workspace=this.store.getWorkspace(workspaceId);if(!workspace)throw new Error("Workspace not found");let files,sourceUri=null,sourceRef=source.ref??null,temp=null;
    try{
      if(source.type==="content")files={"SKILL.md":source.skillMarkdown,"skill.json":source.manifest?JSON.stringify(source.manifest,null,2):undefined};
      else if(source.type==="directory"){sourceUri=await realpath(source.path);const repoRoot=workspace.repo_path?await realpath(workspace.repo_path):null;if(!repoRoot||(sourceUri!==repoRoot&&!sourceUri.startsWith(repoRoot+path.sep))){if(!this.store.consumeOperationApproval(approvalId,"skill.import-directory",sourceUri)){const pending=this.store.listOperationApprovals(workspaceId).find((a)=>a.operation==="skill.import-directory"&&a.resource_id===sourceUri&&a.status==="PENDING")??this.store.createOperationApproval({workspaceId,operation:"skill.import-directory",resourceId:sourceUri,payload:{path:sourceUri}});throw new Error(`External skill directory requires approval ${pending.id}`);}}files=await snapshotDirectory(sourceUri);}
      else if(source.type==="git"){
        const remote=String(source.url??"");if(!remote||remote.length>2048||/[\x00-\x1f\x7f]/.test(remote))throw new Error("Git skill URL is invalid");if(source.ref&&(!/^[A-Za-z0-9][A-Za-z0-9._\/-]{0,199}$/.test(source.ref)||source.ref.includes("..")))throw new Error("Git skill ref is invalid");let approvalResource=remote;
        if(/^https:\/\//i.test(remote)){const parsedUrl=new URL(remote);if(parsedUrl.username||parsedUrl.password)throw new Error("Git skill URL must not embed credentials");}
        else if(!/^git@[^:]+:/i.test(remote)&&!/^ssh:\/\//i.test(remote)){const local=await realpath(remote).catch(()=>null);if(!local||remote.startsWith("-"))throw new Error("Git source must use HTTPS/SSH or an approved local repository");approvalResource=local;}
        if(!this.store.consumeOperationApproval(approvalId,"skill.import-git",approvalResource)){const pending=this.store.listOperationApprovals(workspaceId).find((a)=>a.operation==="skill.import-git"&&a.resource_id===approvalResource&&a.status==="PENDING")??this.store.createOperationApproval({workspaceId,operation:"skill.import-git",resourceId:approvalResource,payload:{repository:approvalResource}});throw new Error(`Git skill import requires approval ${pending.id}`);}
        temp=await mkdtemp(path.join(os.tmpdir(),"lucapi-skill-"));sourceUri=remote;const args=["clone","--depth","1"];if(source.ref)args.push("--branch",source.ref);args.push("--",remote,temp);await exec("git",args,process.cwd());const root=path.resolve(temp,source.subdirectory??".");if(root!==temp&&!root.startsWith(temp+path.sep))throw new Error("Skill subdirectory escapes cloned repository");files=await snapshotDirectory(root);sourceRef=await exec("git",["rev-parse","HEAD"],temp);
      }
      else throw new Error("source.type must be content, directory or git");
      files=Object.fromEntries(Object.entries(files??{}).filter(([,value])=>typeof value==="string"));const parsed=parseSkillMarkdown(files["SKILL.md"]??"");let manifestFile={};if(files["skill.json"])try{manifestFile=JSON.parse(files["skill.json"]);}catch{throw new Error("skill.json is invalid JSON");}
      const manifest=validateManifest({...parsed.frontmatter,...manifestFile},{name:source.name,version:source.version,description:source.description});if(!parsed.body)throw new Error("SKILL.md instructions are empty");const packed=JSON.stringify(files),digest=checksum(packed);
      const existing=this.store.findSkillByName(workspaceId,manifest.name);let skill,version;
      if(existing){const same=this.store.listSkillVersions(existing.id).find((item)=>item.version===manifest.version);if(same){if(same.checksum!==digest)throw new Error(`Skill ${manifest.name} version ${manifest.version} already exists with different content`);version=same;}else version=this.store.addSkillVersion({skillId:existing.id,version:manifest.version,manifest,content:packed,checksum:digest,sourceType:source.type,sourceUri,sourceRef,status:"DRAFT"});skill=existing;}
      else{skill=this.store.createSkill({workspaceId,name:manifest.name,description:manifest.description,instructions:parsed.body,tools:manifest.tools,version:manifest.version,status:"DRAFT",manifest,sourceType:source.type,sourceUri,sourceRef,checksum:digest,content:packed});version=this.store.listSkillVersions(skill.id)[0];}
      const validation=this.validateVersion(version.id,workspace);
      return{skill,version:this.store.getSkillVersion(version.id),validation:{...validation,fileCount:Object.keys(files).length,bytes:Buffer.byteLength(packed)}};
    }finally{if(temp)await rm(temp,{recursive:true,force:true});}
  }
  validateVersion(versionId,workspace){const version=this.store.getSkillVersion(versionId);if(!version)throw new Error("Skill version not found");const manifest=validateManifest(version.manifest),policy=(()=>{try{return JSON.parse(workspace.sandbox_policy||"{}");}catch{return{};}})(),allowed=new Set(policy.allowedCommands??["node","npm","npx","git","cargo","python","python3","pytest","go","make","gitleaks","semgrep","trivy","osv-scanner","sonar-scanner"]),unknownCommands=manifest.commands.filter((command)=>!allowed.has(command)),unknownScanners=manifest.scanners.filter((scanner)=>!SUPPORTED_SCANNERS.has(scanner));let profileError=null;try{if(manifest.scanners.length)validateScanProfileInput({name:manifest.name,hook:manifest.hooks.includes("review")?"review":"manual",scanners:manifest.scanners,policy:manifest.policy,config:manifest.config});}catch(error){profileError=error.message;}const result={ok:unknownCommands.length===0&&unknownScanners.length===0&&!profileError,mode:policy.mode??"local",networkRequested:manifest.sandbox.network===true,unknownCommands,unknownScanners,profileError,executablePackageFiles:false,checkedAt:new Date().toISOString()};this.store.setSkillVersionValidation(versionId,result);return result;}
  async generateSkill({workspaceId,prompt,provider}){
    if(!provider?.complete)throw new Error("A real LLM provider is required to generate a skill");
    const generated=await provider.complete({system:"Design a predictable LucaPi agent skill. Return JSON with manifest and skillMarkdown. Manifest requires name, version, description, hooks, tools, commands, outputs, sandbox. SKILL.md must contain ordered steps with checkable completion criteria and no executable secrets.",user:`Generate a skill for: ${prompt}`});
    return this.importSkill({workspaceId,source:{type:"content",skillMarkdown:generated.skillMarkdown,manifest:generated.manifest}});
  }
  requestPublish(versionId,workspaceId){const version=this.store.getSkillVersion(versionId),skill=this.store.getSkill(version?.skill_id);if(!version||skill?.workspace_id!==workspaceId)throw new Error("Skill version not found in workspace");if(!version.validation_result?.ok)throw new Error("Skill version must pass sandbox policy validation before publication");const existing=this.store.listOperationApprovals(workspaceId).find((a)=>a.operation==="skill.publish"&&a.resource_id===versionId&&a.status==="PENDING");return existing??this.store.createOperationApproval({workspaceId,operation:"skill.publish",resourceId:versionId,payload:{skillId:version.skill_id,version:version.version,checksum:version.checksum}});}
  publish(versionId,workspaceId,approvalId){const version=this.store.getSkillVersion(versionId),skill=this.store.getSkill(version?.skill_id);if(!version||skill?.workspace_id!==workspaceId)throw new Error("Skill version not found in workspace");if(!this.store.consumeOperationApproval(approvalId,"skill.publish",versionId))throw new Error("approved skill.publish operation approval required");let published=this.store.publishSkillVersion(versionId),manifest=version.manifest;let files={};try{files=JSON.parse(version.content);}catch{}const instructions=parseSkillMarkdown(files["SKILL.md"]??published.instructions).body;published=this.store.updateSkill(published.id,{name:manifest.name,description:manifest.description,instructions,tools:manifest.tools,manifest});if(manifest.scanners?.length)for(const hook of manifest.hooks.filter((value)=>["pre-dev","post-dev","review"].includes(value))){const name=`Skill: ${published.name}:${hook}`,profile=this.store.listScanProfiles(workspaceId).find((p)=>p.config?.skillId===published.id&&p.hook===hook),definition={name,hook,scanners:manifest.scanners,policy:manifest.policy,config:{...manifest.config,network:manifest.sandbox?.network===true,skillId:published.id}};if(profile)this.store.updateScanProfile(profile.id,definition);else this.store.createScanProfile({workspaceId,...definition});}return published;}
}

export const BUILTIN_SKILLS=[
  {name:"code-review",version:"1.0.0",description:"Independent diff and acceptance-criteria review",hooks:["review"],tools:["read_file","search_files","git_diff"],commands:["git"],scanners:["code-review"],policy:{blockOn:["critical","high"],failOnScannerError:true,newFindingsOnly:true},outputs:{format:"lucapi-findings-v1"},sandbox:{network:false},instructions:"Review the real diff against acceptance criteria. Report normalized findings with file, line, severity and rule ID. Approve only when evidence supports every criterion."},
  {name:"security-scan",version:"1.0.0",description:"Secret, SAST and dependency security scanning",hooks:["review"],tools:["read_file","search_files","run_command"],commands:["gitleaks","semgrep","trivy","osv-scanner"],scanners:["lucapi-secret","gitleaks","semgrep","trivy","osv-scanner"],policy:{blockOn:["critical","high"],failOnScannerError:true,newFindingsOnly:true},outputs:{format:"sarif-2.1.0"},sandbox:{network:false},instructions:"Run configured security scanners in the review worktree. Normalize findings and block new critical or high severity vulnerabilities."},
  {name:"sonarqube",version:"1.0.0",description:"SonarQube or SonarCloud Quality Gate",hooks:["review"],tools:["run_command"],commands:["sonar-scanner"],scanners:["sonarqube"],policy:{blockOn:["critical","high"],failOnScannerError:true,newFindingsOnly:true},config:{sonarqube:{}},outputs:{format:"lucapi-findings-v1"},sandbox:{network:true},instructions:"Run Sonar analysis, wait for the Compute Engine task, fetch the Quality Gate and normalize bugs, vulnerabilities and security hotspots."}
];
